services:
  # Backend NestJS
  - type: web
    name: ecoa-api
    env: node
    plan: free
    region: ohio
    rootDir: VERDEVIA-BACKEND
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: ecoa-db
          property: connectionString
      - key: KAFKA_BROKERS
        value: "" # Ex: pkc-xxxx.us-east-1.aws.confluent.cloud:9092
      - key: KAFKA_CLIENT_ID
        value: ecoa-api-prod
      - key: KAFKA_CONSUMER_ENABLED
        value: "true"


databases:
  - name: ecoa-db
    plan: free
    region: ohio
    databaseName: ecoa
    user: ecoa_user
