import { ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { hash } from 'argon2';
import { In, Repository } from 'typeorm';
import { CreateAdminDto, SetDocumentPermissionDto, UpdateAdminDto } from './dto/access.dto';
import { AdminAccount, AdminRole } from './entities/admin-account.entity';
import { DocumentPermission } from './entities/document-permission.entity';
@Injectable()
export class AccessService {
  constructor(@InjectRepository(AdminAccount) private readonly admins: Repository<AdminAccount>, @InjectRepository(DocumentPermission) private readonly permissions: Repository<DocumentPermission>) {}
  listAdmins() { return this.admins.find({ order: { createdAt: 'DESC' } }); }
  async createAdmin(dto: CreateAdminDto) { const email = dto.email.trim().toLowerCase(); if (await this.admins.existsBy({ email })) throw new ConflictException('Já existe um administrador com este e-mail.'); return this.admins.save(this.admins.create({ ...dto, email, active: dto.active ?? true, passwordHash: await hash(dto.password) })); }
  async updateAdmin(id: string, dto: UpdateAdminDto, actorId?: string) { const account = await this.admins.findOne({ where: { id }, select: ['id', 'name', 'email', 'role', 'active', 'passwordHash', 'createdAt', 'updatedAt'] }); if (!account) throw new NotFoundException('Administrador não encontrado.'); if (id === actorId && (dto.active === false || (dto.role && dto.role !== 'super_admin'))) throw new ForbiddenException('Você não pode remover o próprio acesso de superadministrador.'); if (dto.email) account.email = dto.email.trim().toLowerCase(); if (dto.name !== undefined) account.name = dto.name; if (dto.role !== undefined) account.role = dto.role; if (dto.active !== undefined) account.active = dto.active; if (dto.password) account.passwordHash = await hash(dto.password); return this.admins.save(account); }
  async removeAdmin(id: string, actorId?: string) { if (id === actorId) throw new ForbiddenException('Você não pode excluir a própria conta.'); const account = await this.admins.findOneBy({ id }); if (!account) throw new NotFoundException('Administrador não encontrado.'); if (account.role === 'super_admin' && await this.admins.countBy({ role: 'super_admin', active: true }) <= 1) throw new ForbiddenException('O último superadministrador ativo não pode ser excluído.'); await this.admins.remove(account); return { success: true }; }
  listPermissions() { return this.permissions.find({ order: { filename: 'ASC' } }); }
  async ensureDocumentPermissions(documents: Array<{ documentId: string; filename: string }>) { const existing = new Set((await this.permissions.find({ select: ['documentId'] })).map((item) => item.documentId)); const missing = documents.filter((item) => !existing.has(item.documentId)).map((item) => this.permissions.create({ documentId: item.documentId, filename: item.filename, minimumRole: 'admin', explanationAllowed: true })); if (missing.length) await this.permissions.save(missing); }
  async setPermission(dto: SetDocumentPermissionDto, updatedBy?: string) { const current = await this.permissions.findOneBy({ documentId: dto.documentId }); return this.permissions.save(this.permissions.create({ ...current, ...dto, updatedBy, blockReason: dto.explanationAllowed ? undefined : dto.blockReason?.trim() || 'Explicação bloqueada pela administração.' })); }
  async filterAllowedDocuments(documentIds: string[], role?: string) { if (!documentIds.length) return { allowed: [], blocked: [] as DocumentPermission[] }; const records = await this.permissions.find({ where: { documentId: In(documentIds) } }); const map = new Map(records.map((item) => [item.documentId, item])); const rank: Record<AdminRole, number> = { admin: 1, super_admin: 2 }; const userRank = rank[role as AdminRole] ?? 0; const blocked: DocumentPermission[] = []; const allowed = documentIds.filter((id) => { const permission = map.get(id); const canUse = Boolean(permission?.explanationAllowed && userRank >= rank[permission.minimumRole]); if (!canUse && permission) blocked.push(permission); return canUse; }); return { allowed, blocked }; }
}
