'use client';

import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { BriefcaseBusiness, ChevronRight, CircleUserRound, FileText, LayoutDashboard, LogOut, Plus, Search, ShieldCheck, Trash2, UsersRound, X } from 'lucide-react';
import AuthService, { AuthUser } from '@/services/auth.service';
import JobsService, { Application, Job } from '@/services/jobs.service';

type View = 'overview' | 'jobs' | 'applications' | 'governance';
const statusLabel: Record<string, string> = { applied: 'Recebida', screening: 'Triagem', interview: 'Entrevista', approved: 'Aprovada', rejected: 'Encerrada' };

export default function CareersAdminPanel() {
  const router = useRouter();
  const [user, setUser] = useState<AuthUser | null>(null);
  const [view, setView] = useState<View>('overview');
  const [jobs, setJobs] = useState<Job[]>([]);
  const [applications, setApplications] = useState<Application[]>([]);
  const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState('');
  const [jobModal, setJobModal] = useState<Job | 'new' | null>(null);
  const [selectedApplication, setSelectedApplication] = useState<Application | null>(null);
  const isSuperAdmin = user?.role?.toUpperCase().replace('-', '_') === 'SUPER_ADMIN';

  const load = async () => {
    setLoading(true);
    const [jobResult, applicationResult] = await Promise.allSettled([JobsService.getJobs(), JobsService.getApplications()]);
    if (jobResult.status === 'fulfilled') setJobs(jobResult.value);
    if (applicationResult.status === 'fulfilled') setApplications(applicationResult.value);
    setLoading(false);
  };

  useEffect(() => {
    const token = localStorage.getItem('VERDEVIA_token');
    const stored = localStorage.getItem('VERDEVIA_user');
    if (!token || !stored) { router.replace('/'); return; }
    try { setUser(JSON.parse(stored)); load(); } catch { AuthService.clearSession(); router.replace('/'); }
  }, [router]);

  const filteredJobs = useMemo(() => jobs.filter(j => `${j.title} ${j.location}`.toLowerCase().includes(query.toLowerCase())), [jobs, query]);
  const filteredApplications = useMemo(() => applications.filter(a => `${a.candidate?.name} ${a.candidate?.email} ${a.job?.title}`.toLowerCase().includes(query.toLowerCase())), [applications, query]);
  const openJobs = jobs.filter(j => j.status === 'active').length;
  const pending = applications.filter(a => ['applied', 'screening'].includes(a.status)).length;

  const logout = () => { AuthService.clearSession(); router.replace('/'); };
  const removeJob = async (job: Job) => { if (!isSuperAdmin || !confirm(`Excluir a vaga “${job.title}”?`)) return; await JobsService.deleteJob(job.id); await load(); };

  return <main className="admin-shell min-h-screen bg-background text-foreground lg:flex">
    <aside className="border-b border-border bg-card lg:fixed lg:inset-y-0 lg:w-64 lg:border-b-0 lg:border-r">
      <div className="flex h-16 items-center justify-between border-b border-border px-5"><div><strong className="block text-sm">VERDEVIA Careers</strong><span className="text-[10px] font-bold uppercase tracking-wider text-primary">Administração</span></div><ShieldCheck className="h-5 w-5 text-primary" /></div>
      <nav className="flex gap-1 overflow-x-auto p-3 lg:block lg:space-y-1">{([
        ['overview','Visão geral',LayoutDashboard],['jobs','Vagas',BriefcaseBusiness],['applications','Candidaturas',UsersRound],...(isSuperAdmin ? [['governance','Governança',ShieldCheck]] : [])
      ] as [string, string, any][]).map(([id,label,Icon]) => <button key={id} onClick={() => setView(id as View)} className={`flex min-w-max items-center gap-3 rounded-lg px-4 py-3 text-sm font-semibold lg:w-full ${view === id ? 'bg-primary/10 text-primary' : 'text-muted-foreground hover:bg-muted hover:text-foreground'}`}><Icon className="h-4 w-4" />{label}</button>)}</nav>
      <div className="hidden border-t border-border p-4 lg:absolute lg:inset-x-0 lg:bottom-0 lg:block"><div className="mb-3 flex items-center gap-3"><CircleUserRound className="h-8 w-8 text-primary"/><div className="min-w-0"><p className="truncate text-xs font-bold">{user?.name}</p><p className="text-[10px] uppercase text-muted-foreground">{isSuperAdmin ? 'Super Admin' : 'Admin'}</p></div></div><button onClick={logout} className="flex items-center gap-2 text-xs font-semibold text-muted-foreground hover:text-destructive"><LogOut className="h-4 w-4"/>Sair</button></div>
    </aside>

    <div className="min-w-0 flex-1 lg:ml-64"><header className="flex min-h-16 items-center justify-between border-b border-border bg-background/90 px-4 backdrop-blur sm:px-8"><div><p className="text-sm font-bold">{view === 'overview' ? 'Visão geral' : view === 'jobs' ? 'Gestão de vagas' : view === 'applications' ? 'Candidaturas' : 'Governança'}</p><p className="text-xs text-muted-foreground">Operação do portal de carreiras</p></div><button onClick={logout} className="p-2 lg:hidden"><LogOut className="h-4 w-4"/></button></header>
      <div className="mx-auto max-w-7xl p-4 sm:p-8">
        {loading ? <div className="py-24 text-center text-sm text-muted-foreground">Carregando dados do recrutamento…</div> : <>
          {view === 'overview' && <Overview jobs={jobs.length} openJobs={openJobs} applications={applications.length} pending={pending} recent={applications.slice(0,5)} onNavigate={setView} />}
          {view === 'jobs' && <><Toolbar query={query} setQuery={setQuery} placeholder="Buscar vagas"><button onClick={() => setJobModal('new')} className="flex h-10 items-center gap-2 rounded-lg bg-primary px-4 text-sm font-bold text-primary-foreground"><Plus className="h-4 w-4"/>Nova vaga</button></Toolbar><div className="overflow-hidden rounded-xl border border-border bg-card"><table className="w-full min-w-[720px] text-left"><thead className="bg-muted/50 text-xs text-muted-foreground"><tr><th className="p-4">Vaga</th><th>Local</th><th>Status</th><th>Candidaturas</th><th className="pr-4 text-right">Ações</th></tr></thead><tbody>{filteredJobs.map(job => <tr key={job.id} className="border-t border-border"><td className="p-4"><button onClick={() => setJobModal(job)} className="font-bold hover:text-primary">{job.title}</button></td><td className="text-sm text-muted-foreground">{job.location || 'Não informado'}</td><td><Status value={job.status}/></td><td className="text-sm">{applications.filter(a=>a.jobId===job.id).length}</td><td className="pr-4 text-right"><button onClick={()=>setJobModal(job)} className="p-2 text-muted-foreground hover:text-primary"><FileText className="h-4 w-4"/></button>{isSuperAdmin && <button onClick={()=>removeJob(job)} className="p-2 text-muted-foreground hover:text-destructive"><Trash2 className="h-4 w-4"/></button>}</td></tr>)}</tbody></table></div></>}
          {view === 'applications' && <><Toolbar query={query} setQuery={setQuery} placeholder="Buscar pessoa, e-mail ou vaga"/><div className="grid gap-3">{filteredApplications.map(app => <button key={app.id} onClick={()=>setSelectedApplication(app)} className="flex items-center justify-between rounded-xl border border-border bg-card p-5 text-left hover:border-primary/50"><div><p className="font-bold">{app.candidate?.name || 'Candidato'}</p><p className="mt-1 text-sm text-muted-foreground">{app.job?.title} · {app.candidate?.email}</p></div><div className="flex items-center gap-4"><Status value={app.status}/><ChevronRight className="h-4 w-4 text-muted-foreground"/></div></button>)}</div></>}
          {view === 'governance' && isSuperAdmin && <Governance user={user} jobs={jobs} applications={applications}/>} </>}
      </div>
    </div>
    {jobModal && <JobEditor value={jobModal} onClose={()=>setJobModal(null)} onSaved={async()=>{setJobModal(null);await load();}}/>}
    {selectedApplication && <ApplicationPanel application={selectedApplication} onClose={()=>setSelectedApplication(null)} onSaved={async()=>{setSelectedApplication(null);await load();}}/>}
  </main>;
}

function Overview({jobs,openJobs,applications,pending,recent,onNavigate}:{jobs:number;openJobs:number;applications:number;pending:number;recent:Application[];onNavigate:(v:View)=>void}) { return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Vagas abertas',openJobs],['Total de vagas',jobs],['Candidaturas',applications],['Aguardando triagem',pending]].map(([label,value])=><div key={label} className="rounded-xl border border-border bg-card p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-3 text-3xl font-black">{value}</p></div>)}</div><div className="mt-8 rounded-xl border border-border bg-card"><div className="flex items-center justify-between border-b border-border p-5"><h2 className="font-bold">Candidaturas recentes</h2><button onClick={()=>onNavigate('applications')} className="text-sm font-bold text-primary">Ver todas</button></div>{recent.map(a=><div key={a.id} className="flex items-center justify-between border-b border-border px-5 py-4 last:border-0"><div><p className="text-sm font-bold">{a.candidate?.name}</p><p className="text-xs text-muted-foreground">{a.job?.title}</p></div><Status value={a.status}/></div>)}</div></> }
function Toolbar({query,setQuery,placeholder,children}:{query:string;setQuery:(q:string)=>void;placeholder:string;children?:React.ReactNode}) { return <div className="mb-5 flex flex-col justify-between gap-3 sm:flex-row"><label className="relative max-w-lg flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={placeholder} className="h-10 w-full rounded-lg border border-border bg-card pl-10 pr-3 text-sm outline-none focus:border-primary"/></label>{children}</div> }
function Status({value}:{value:string}) { return <span className={`inline-flex rounded-full px-2.5 py-1 text-[11px] font-bold ${['active','approved'].includes(value)?'bg-emerald-500/10 text-emerald-600':['rejected','closed'].includes(value)?'bg-red-500/10 text-red-500':'bg-amber-500/10 text-amber-600'}`}>{statusLabel[value] || (value === 'active' ? 'Ativa' : value)}</span> }

function JobEditor({value,onClose,onSaved}:{value:Job|'new';onClose:()=>void;onSaved:()=>void}) { const editing=value!=='new'; const job=editing?value:null; const [saving,setSaving]=useState(false); const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);const d=new FormData(e.currentTarget);const input={title:String(d.get('title')),description:String(d.get('description')),requirements:String(d.get('requirements')),benefits:String(d.get('benefits')),location:String(d.get('location')),salary:Number(d.get('salary'))||undefined};if(editing) await JobsService.updateJob(job!.id,{...input,status:String(d.get('status'))});else await JobsService.createJob(input);onSaved();};return <Modal title={editing?'Editar vaga':'Nova vaga'} onClose={onClose}><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><Field label="Título"><input name="title" required defaultValue={job?.title} className="career-input"/></Field><Field label="Local/modelo"><input name="location" defaultValue={job?.location} className="career-input"/></Field><div className="sm:col-span-2"><Field label="Descrição"><textarea name="description" required defaultValue={job?.description} className="career-input min-h-28"/></Field></div><Field label="Requisitos"><textarea name="requirements" defaultValue={job?.requirements} className="career-input min-h-24"/></Field><Field label="Benefícios"><textarea name="benefits" defaultValue={job?.benefits} className="career-input min-h-24"/></Field><Field label="Salário"><input name="salary" type="number" defaultValue={job?.salary} className="career-input"/></Field>{editing&&<Field label="Status"><select name="status" defaultValue={job!.status} className="career-input"><option value="active">Ativa</option><option value="draft">Rascunho</option><option value="closed">Encerrada</option></select></Field>}<button disabled={saving} className="h-11 rounded-lg bg-primary font-bold text-primary-foreground sm:col-span-2">{saving?'Salvando…':'Salvar vaga'}</button></form></Modal> }
function ApplicationPanel({application,onClose,onSaved}:{application:Application;onClose:()=>void;onSaved:()=>void}) { const [status,setStatus]=useState(application.status);const [feedback,setFeedback]=useState(application.feedback||'');const save=async()=>{await JobsService.updateApplicationStatus(application.id,status,feedback);onSaved();};const phone=application.candidate?.phones?.[0];return <Modal title="Detalhes da candidatura" onClose={onClose}><div className="space-y-6"><div><h3 className="text-xl font-bold">{application.candidate?.name}</h3><p className="text-sm text-muted-foreground">{application.candidate?.email}{phone?` · +${phone.ddi} ${phone.ddd} ${phone.number}`:''}</p><p className="mt-2 text-sm font-semibold text-primary">{application.job?.title}</p></div><div className="flex gap-3">{application.candidate?.resumeUrl&&<a target="_blank" href={application.candidate.resumeUrl} className="rounded-lg border border-border px-3 py-2 text-sm font-bold">Currículo</a>}{application.candidate?.linkedInUrl&&<a target="_blank" href={application.candidate.linkedInUrl} className="rounded-lg border border-border px-3 py-2 text-sm font-bold">LinkedIn</a>}</div><Field label="Etapa"><select value={status} onChange={e=>setStatus(e.target.value)} className="career-input">{Object.entries(statusLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field label="Feedback interno"><textarea value={feedback} onChange={e=>setFeedback(e.target.value)} className="career-input min-h-28"/></Field><button onClick={save} className="h-11 w-full rounded-lg bg-primary font-bold text-primary-foreground">Atualizar candidatura</button></div></Modal> }
function Governance({user,jobs,applications}:{user:AuthUser|null;jobs:Job[];applications:Application[]}) { return <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-xl border border-border bg-card p-6"><ShieldCheck className="h-6 w-6 text-primary"/><h2 className="mt-4 text-xl font-bold">Acesso Super Admin</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Você pode excluir vagas, supervisionar todo o funil e acessar configurações sensíveis do recrutamento.</p><div className="mt-6 rounded-lg bg-muted p-4 text-sm"><strong>{user?.name}</strong><p className="text-muted-foreground">{user?.email}</p></div></section><section className="rounded-xl border border-border bg-card p-6"><h2 className="font-bold">Integridade operacional</h2><dl className="mt-5 space-y-4 text-sm"><div className="flex justify-between"><dt className="text-muted-foreground">Vagas arquivadas</dt><dd className="font-bold">{jobs.filter(j=>j.status==='closed').length}</dd></div><div className="flex justify-between"><dt className="text-muted-foreground">Processos encerrados</dt><dd className="font-bold">{applications.filter(a=>['approved','rejected'].includes(a.status)).length}</dd></div><div className="flex justify-between"><dt className="text-muted-foreground">Retenção de candidatos</dt><dd className="font-bold">6 meses</dd></div></dl></section></div> }
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}) { return <div className="fixed inset-0 z-[80] overflow-y-auto bg-black/55 p-4 backdrop-blur-sm"><div className="mx-auto my-8 max-w-2xl rounded-2xl border border-border bg-background p-6 shadow-2xl"><div className="mb-6 flex items-center justify-between"><h2 className="text-xl font-black">{title}</h2><button onClick={onClose} className="rounded-lg p-2 hover:bg-muted"><X className="h-4 w-4"/></button></div>{children}</div></div> }
function Field({label,children}:{label:string;children:React.ReactNode}) { return <label className="block"><span className="mb-2 block text-xs font-bold text-muted-foreground">{label}</span>{children}</label> }
