'use client';

import { useEffect, useState } from 'react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Bot, Download, FileText, Files, Gauge, RefreshCw, TriangleAlert } from 'lucide-react';
import DashboardLayout from '@/components/DashboardLayout';
import { getAiOperations, type AiOperationsSnapshot } from '@/services/admin-control.service';
import { downloadXlsx, printPdfReport } from '@/lib/admin-report';

const empty: AiOperationsSnapshot = { documents: [], tokensUsed: 0, tokenLimit: 1_000_000, requestsToday: 0, errorLogs: [] };
export default function AiAdministrationPage() {
  const [data, setData] = useState(empty); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); getAiOperations().then(setData).catch(() => setData(empty)).finally(() => setLoading(false)); };
  useEffect(load, []);
  const chartData = data.documents.slice(0, 7).map((document) => ({ name: document.filename.length > 12 ? `${document.filename.slice(0, 12)}…` : document.filename, chunks: document.chunks }));
  const summary = [['Arquivos indexados', String(data.documents.length)], ['Tokens estimados', data.tokensUsed.toLocaleString('pt-BR')], ['Erros recentes', String(data.errorLogs.length)]] as Array<[string,string]>;
  return <DashboardLayout title="Operações de IA" role="super-admin"><div className="space-y-6"><section className="rounded-3xl border border-violet-500/25 bg-violet-500/5 p-6"><p className="text-[10px] font-black uppercase tracking-[.22em] text-violet-300">Microserviço: ai-operations</p><h1 className="mt-2 text-2xl font-black">Observabilidade e base de conhecimento da IA</h1><p className="mt-2 text-sm text-slate-400">Arquivos RAG, consumo estimado, requisições e logs são isolados do domínio de planos e acessos.</p></section><div className="grid gap-4 md:grid-cols-4"><Card icon={<Files/>} label="Arquivos" value={data.documents.length}/><Card icon={<Gauge/>} label="Tokens estimados" value={data.tokensUsed.toLocaleString('pt-BR')}/><Card icon={<Bot/>} label="Requisições hoje" value={data.requestsToday}/><Card icon={<TriangleAlert/>} label="Logs de erro" value={data.errorLogs.length}/></div><section className="rounded-3xl border border-white/10 bg-card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-black">Volume indexado por arquivo</h2><p className="text-xs text-slate-500">Trechos RAG processados pelo gateway de IA.</p></div><div className="flex gap-2"><button onClick={load} className="rounded-xl border border-white/10 p-2" title="Atualizar"><RefreshCw size={16} className={loading ? 'animate-spin' : ''}/></button><button onClick={() => downloadXlsx('operacoes-ia', data.documents.map((d) => ({ Arquivo: d.filename, Tipo: d.contentType, Trechos: d.chunks, Modalidades: d.modalities.join(', ') })))} className="flex items-center gap-2 rounded-xl border border-white/10 px-3 py-2 text-xs"><Download size={14}/> XLSX</button><button onClick={() => printPdfReport('Relatório de operações de IA', summary, chartData.map((row) => ({ label: row.name, value: row.chunks })))} className="flex items-center gap-2 rounded-xl bg-primary px-3 py-2 text-xs font-bold text-black"><FileText size={14}/> PDF</button></div></div><div className="mt-5 h-72"><ResponsiveContainer><BarChart data={chartData}><CartesianGrid strokeDasharray="3 3" stroke="#ffffff12"/><XAxis dataKey="name" tick={{ fontSize: 10 }}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="chunks" fill="#8b5cf6" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></section><section className="rounded-3xl border border-white/10 bg-card p-5"><h2 className="font-black">Log de erros do gateway</h2>{data.errorLogs.length ? data.errorLogs.map((log) => <div key={log.id}>{log.message}</div>) : <p className="mt-3 text-sm text-slate-500">Nenhum erro reportado pelo contrato de operações de IA.</p>}</section></div></DashboardLayout>;
}
function Card({ icon, label, value }: { icon: React.ReactNode; label: string; value: string | number }) { return <div className="rounded-2xl border border-white/10 bg-card p-5"><div className="mb-3 text-violet-300">{icon}</div><p className="text-xs text-slate-500">{label}</p><p className="text-2xl font-black">{value}</p></div>; }
